//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_DocumentosAfiliacion_FileToBase64
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileToBase64Request", Namespace="http://schemas.datacontract.org/2004/07/WS_ArchivosDTO")]
    public partial class FileToBase64Request : object
    {
        
        private string filePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filePath
        {
            get
            {
                return this.filePathField;
            }
            set
            {
                this.filePathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileToBase64Response", Namespace="http://schemas.datacontract.org/2004/07/WS_ArchivosDTO")]
    public partial class FileToBase64Response : object
    {
        
        private string base64StringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string base64String
        {
            get
            {
                return this.base64StringField;
            }
            set
            {
                this.base64StringField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws_DocumentosAfiliacion_FileToBase64.IFileToBase64")]
    public interface IFileToBase64
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileToBase64/fileToBase64", ReplyAction="http://tempuri.org/IFileToBase64/fileToBase64Response")]
        System.Threading.Tasks.Task<ws_DocumentosAfiliacion_FileToBase64.FileToBase64Response> fileToBase64Async(ws_DocumentosAfiliacion_FileToBase64.FileToBase64Request Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IFileToBase64Channel : ws_DocumentosAfiliacion_FileToBase64.IFileToBase64, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FileToBase64Client : System.ServiceModel.ClientBase<ws_DocumentosAfiliacion_FileToBase64.IFileToBase64>, ws_DocumentosAfiliacion_FileToBase64.IFileToBase64
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FileToBase64Client(EndpointConfiguration endpointConfiguration) : 
                base(FileToBase64Client.GetBindingForEndpoint(endpointConfiguration), FileToBase64Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileToBase64Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FileToBase64Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileToBase64Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FileToBase64Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileToBase64Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ws_DocumentosAfiliacion_FileToBase64.FileToBase64Response> fileToBase64Async(ws_DocumentosAfiliacion_FileToBase64.FileToBase64Request Request)
        {
            return base.Channel.fileToBase64Async(Request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFileToBase64))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IFileToBase64))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFileToBase64))
            {
                return new System.ServiceModel.EndpointAddress("http://desaiis01/WS_DocumentosAfiliacion/FileToBase64.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IFileToBase64))
            {
                return new System.ServiceModel.EndpointAddress("https://desaiis01.invercap.icap/WS_DocumentosAfiliacion/FileToBase64.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFileToBase64,
            
            BasicHttpsBinding_IFileToBase64,
        }
    }
}
